[tool.poetry]
name = "repl_nix_EPS-Python"
version = "0.1.0"
description = ""
authors = ["lcomunax <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
numpy = "^1.22.4"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
